### ISSUE TITLE
Overload help - NRE

### ISSUE THREAD

**Issue by kindermannhubert** [waf/PrettyPrompt#217]
NRE for overload for a member without any xml doc.
Type in CSharpRepl:
```C#
int M() => 0;
M(
```

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
   at PrettyPrompt.Panes.OverloadPane.UpdateSelectedItem()
   at PrettyPrompt.Panes.OverloadPane.<TryOpen>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PrettyPrompt.Panes.OverloadPane.<PrettyPrompt-Consoles-IKeyPressHandler-OnKeyUp>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PrettyPrompt.Prompt.<>c__DisplayClass9_0.<<ReadLineAsync>g__InterpretKeyPress|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PrettyPrompt.Prompt.<ReadLineAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CSharpRepl.ReadEvalPrintLoop.<RunAsync>d__4.MoveNext() in 
```

**Comment by kindermannhubert** [comment]
This is not a bug but it's caused by invalid usage of PrettyPrompt API from CSharpRepl (and only in my local edited version).
Although we should add argument validation inside `OverloadItem` ctor.
