### ISSUE TITLE
Pasting 🤦🏼‍♂️character into repl throws exception and exits repl

### ISSUE THREAD

**Issue by MikeSchurman** [waf/PrettyPrompt#270]
### Version

0.6.5

### What happened?

I tried pasting the 🤦🏼‍♂️character into the repl and it throws an exception:

![image](https://github.com/waf/CSharpRepl/assets/7268923/156ea02c-1b74-4782-bbe2-f8aa8a6955ed)

```
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.──────────────┬──────────────────┐
   at PrettyPrompt.Rendering.Screen.PositionCursor(Screen screen, ConsoleCoordinate cursor)
   at PrettyPrompt.Rendering.Screen..ctor(Int32 width, Int32 height, ConsoleCoordinate cursor, ScreenArea[] screenAreas) │
   at PrettyPrompt.Renderer.<RenderOutput>g__Redraw|7_0(<>c__DisplayClass7_0&)
   at PrettyPrompt.Renderer.RenderOutput(PromptResult result, CodePane codePane, OverloadPane overloadPane, CompletionPane completionPane, IReadOnlyCollection`1 highlights, KeyPress key)│ AppContext               │
   at PrettyPrompt.Prompt.RenderSyntaxHighlightedOutput(Renderer renderer, CodePane codePane, OverloadPane overloadPane, CompletionPane completionPane, KeyPress key, String inputText, PromptResult result)─────────┘
   at PrettyPrompt.Prompt.ReadLineAsync()
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\ReadEvalPrintLoop.cs:line 49
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 68
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 74
   at CSharpRepl.Program.<Main>(String[] args)
   ```

**Comment by tats-u** [comment]
- ⚠️ (U+26A0 U+FE0F) → No crash
- 🤦 (U+1F926) → No crash
- ***🤦🏼 (U+1F926 U+1F3FC) → CRASH***
- ***🤦‍♂ (U+1F926 U+200D U+2642) → CRASH***
- 🤦️️ (U+1F926 U+FE0F) → No crash
- 𠮟 (U+20B9F; means "scold") → No crash
- 禰 (U+79B0) → No crash
- ***禰󠄀 (U+79B0 U+E0100; used in the name of the sister of the main character of [Daemon Slayer: Kimetsu no Yaiba](https://en.wikipedia.org/wiki/Demon_Slayer:_Kimetsu_no_Yaiba)) → CRASH***
- 侮︀ (U+4FAE U+FE00) → No crash

**Comment by tats-u** [comment]
https://github.com/waf/PrettyPrompt/blob/4245c197b21500a634d9fbe29cad0e9d5f4753cc/src/PrettyPrompt/Rendering/Screen.cs#L100

This assertion fails.

https://github.com/waf/PrettyPrompt/blob/4245c197b21500a634d9fbe29cad0e9d5f4753cc/src/PrettyPrompt/Rendering/UnicodeWidth.cs#L244

This returns more than two and the returned value is set to `.ElementWidth`.

**Comment by waf** [comment]
I've released a version that improves this by quite a lot. There are still a few gremlins to sort out, but I think the latest release's handling is much more correct:

<img width="455" height="540" alt="Image" src="https://github.com/user-attachments/assets/883f8c7a-d747-4900-8bae-3e3ad3358c55" />

It looks like there may still be some cursor navigation issues on ⚠️, but I should be able to figure that out shortly.

**Comment by tats-u** [comment]
Great news, but U+FF9E–U+FE9F in "ﾊﾟｸﾞ" (U+FF8A U+FF9F U+FF78 U+FF9E) (= パグ; means pug dog in Japanese) seem not to be counted as 1 character width respectively. They are grapheme extenders but letters (Lm). This word should be counted as 4 character width, not 2.

https://github.com/microsoft/terminal/issues/18087
